
# Crear cuenta
gRPC localhost:9090/CuentaGrpcService/CrearCuenta
{
  "usuario_id": "123",
  "saldo_inicial": 1000.00
}
response:
{
	"id": "5c294788-f24d-4d21-b2eb-dbc1d35915a1",
	"usuario_id": "123",
	"saldo": 1000,
	"estado": "ACTIVA",
	"fecha_creacion": "2025-02-23T01:39:01.706032701"
}

# Actualizar cuenta
gRPC localhost:9090/CuentaGrpcService/ActualizarCuenta
{
  "id": "5c294788-f24d-4d21-b2eb-dbc1d35915a1",
  "saldo": 1500.00,
  "estado": "ACTIVA"
}

# Consultar cuenta
gRPC localhost:9090/CuentaGrpcService/ConsultarCuenta
{
  "id": "5c294788-f24d-4d21-b2eb-dbc1d35915a1"
}

# Listar cuentas por usuario
gRPC localhost:9090/CuentaGrpcService/ListarCuentas
{
  "usuario_id": "123"
}


